# Generated by Django 3.1.1 on 2020-09-22 00:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=55)),
                ('continent', models.CharField(max_length=15)),
                ('population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CovidDataRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=8, null=True, unique_for_date='date')),
                ('continent', models.CharField(max_length=15, null=True, unique_for_date='date')),
                ('location', models.CharField(max_length=55, null=True, unique_for_date='date')),
                ('date', models.DateField()),
                ('total_cases', models.IntegerField(null=True)),
                ('new_cases', models.IntegerField(default=0, null=True)),
                ('new_cases_smoothed', models.FloatField(null=True)),
                ('total_deaths', models.IntegerField(null=True)),
                ('new_deaths', models.IntegerField(default=0, null=True)),
                ('new_deaths_smoothed', models.FloatField(null=True)),
                ('total_cases_per_million', models.FloatField(null=True)),
                ('new_cases_per_million', models.FloatField(null=True)),
                ('new_cases_smoothed_per_million', models.FloatField(null=True)),
                ('total_deaths_per_million', models.FloatField(null=True)),
                ('new_deaths_per_million', models.FloatField(null=True)),
                ('new_deaths_smoothed_per_million', models.FloatField(null=True)),
                ('new_tests', models.IntegerField(default=0, null=True)),
                ('total_tests', models.IntegerField(null=True)),
                ('total_tests_per_thousand', models.FloatField(null=True)),
                ('new_tests_per_thousand', models.FloatField(null=True)),
                ('new_tests_smoothed', models.FloatField(null=True)),
                ('new_tests_smoothed_per_thousand', models.FloatField(null=True)),
                ('tests_per_case', models.FloatField(null=True)),
                ('positive_rate', models.FloatField(null=True)),
                ('tests_units', models.TextField(null=True)),
                ('stringency_index', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('population', models.PositiveBigIntegerField(null=True)),
                ('population_density', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
                ('median_age', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('aged_65_older', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('aged_70_older', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('gdp_per_capita', models.DecimalField(decimal_places=3, max_digits=9, null=True)),
                ('extreme_poverty', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('cardiovasc_death_rate', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
                ('diabetes_prevalence', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('female_smokers', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('male_smokers', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('handwashing_facilities', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('hospital_beds_per_thousand', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('life_expectancy', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('human_development_index', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
            ],
            options={
                'ordering': ['iso_code', 'date'],
                'unique_together': {('iso_code', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CovidDataClean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='continents', to='data.coviddataraw')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dates', to='data.coviddataraw')),
                ('iso_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='iso_codes', to='data.coviddataraw')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='locations', to='data.coviddataraw')),
                ('new_cases', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cases', to='data.coviddataraw')),
                ('new_deaths', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deaths', to='data.coviddataraw')),
                ('new_tests', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tests', to='data.coviddataraw')),
            ],
        ),
    ]
