# Generated by Django 3.1.1 on 2020-09-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=55)),
                ('continent', models.CharField(max_length=15)),
                ('population', models.IntegerField()),
            ],
        ),
    ]
