# Generated by Django 3.1.3 on 2020-11-16 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_squashed_0013_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryStats',
            fields=[
                ('iso_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.country')),
                ('total_cases', models.FloatField(null=True)),
                ('total_deaths', models.FloatField(null=True)),
                ('total_tests', models.FloatField(null=True)),
            ],
        ),
    ]
