# Generated by Django 3.1.2 on 2020-10-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
        create table data_coviddataraw
        (
            iso_code text,
            continent text,
            location text not null,
            date date not null,
            total_cases numeric,
            new_cases numeric,
            new_cases_smoothed numeric,
            total_deaths numeric,
            new_deaths numeric,
            new_deaths_smoothed numeric,
            total_cases_per_million numeric,
            new_cases_per_million numeric,
            new_cases_smoothed_per_million numeric,
            total_deaths_per_million numeric,
            new_deaths_per_million numeric,
            new_deaths_smoothed_per_million numeric,
            total_tests numeric,
            new_tests numeric,
            total_tests_per_thousand numeric,
            new_tests_per_thousand numeric,
            new_tests_smoothed numeric,
            new_tests_smoothed_per_thousand numeric,
            tests_per_case numeric,
            positive_rate numeric,
            tests_units text,
            stringency_index numeric,
            population numeric,
            population_density numeric,
            median_age numeric,
            aged_65_older numeric,
            aged_70_older numeric,
            gdp_per_capita numeric,
            extreme_poverty numeric,
            cardiovasc_death_rate numeric,
            diabetes_prevalence numeric,
            female_smokers numeric,
            male_smokers numeric,
            handwashing_facilities numeric,
            hospital_beds_per_thousand numeric,
            life_expectancy numeric,
            human_development_index numeric,
            constraint data_coviddataraw_pk
                primary key (date, location)
            );

        alter table data_coviddataraw owner to "DataTitans";
        """, """DROP TABLE IF EXISTS data_coviddataraw""")
    ]
