# Generated by Django 3.1.1 on 2020-09-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200921_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddataclean',
            name='continent',
            field=models.CharField(max_length=15, unique_for_date='date'),
        ),
        migrations.AlterField(
            model_name='coviddataclean',
            name='iso_code',
            field=models.CharField(max_length=8, unique_for_date='date'),
        ),
        migrations.AlterField(
            model_name='coviddataclean',
            name='location',
            field=models.CharField(max_length=55, unique_for_date='date'),
        ),
        migrations.AlterField(
            model_name='coviddataclean',
            name='new_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coviddataclean',
            name='new_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coviddataclean',
            name='new_tests',
            field=models.IntegerField(default=0),
        ),
    ]
