# Generated by Django 3.1.2 on 2020-10-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_created_clean_data_view'),
    ]

    operations = [
        migrations.RunSQL("""
        create materialized view if not exists data_country as
        SELECT DISTINCT ON (data_coviddataclean.iso_code) data_coviddataclean.iso_code,
                                                          data_coviddataclean.location AS name,
                                                          data_coviddataclean.continent,
                                                          data_coviddataclean.population
        FROM data_coviddataclean
        ORDER BY data_coviddataclean.iso_code;

        alter materialized view data_country owner to "DataTitans";
        """, """DROP MATERIALIZED VIEW IF EXISTS data_country""")
    ]
