# Generated by Django 3.1.1 on 2020-09-22 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200921_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coviddataclean',
            name='new_cases',
        ),
    ]
