# Generated by Django 3.1.1 on 2020-09-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200916_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidDataClean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=8, unique_for_date='date')),
                ('continent', models.CharField(max_length=15, unique_for_date='date')),
                ('location', models.CharField(max_length=55, unique_for_date='date')),
                ('date', models.DateField()),
                ('new_cases', models.IntegerField(default=0)),
                ('total_cases', models.IntegerField()),
                ('new_deaths', models.IntegerField(default=0)),
                ('total_deaths', models.IntegerField()),
                ('new_tests', models.IntegerField(default=0)),
                ('total_tests', models.IntegerField()),
            ],
        ),
    ]
