# Generated by Django 3.1.1 on 2020-09-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_coviddataclean'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidDataRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=8, unique_for_date='date')),
                ('continent', models.CharField(max_length=15, unique_for_date='date')),
                ('location', models.CharField(max_length=55, unique_for_date='date')),
                ('date', models.DateField()),
                ('total_cases', models.IntegerField()),
                ('new_cases', models.IntegerField(default=0)),
                ('new_cases_smoothed', models.FloatField()),
                ('total_deaths', models.IntegerField()),
                ('new_deaths', models.IntegerField(default=0)),
                ('new_deaths_smoothed', models.FloatField()),
                ('total_cases_per_million', models.FloatField()),
                ('new_cases_per_million', models.FloatField()),
                ('new_cases_smoothed_per_million', models.FloatField()),
                ('total_deaths_per_million', models.FloatField()),
                ('new_deaths_per_million', models.FloatField()),
                ('new_deaths_smoothed_per_million', models.FloatField()),
                ('new_tests', models.IntegerField(default=0)),
                ('total_tests', models.IntegerField()),
                ('total_tests_per_thousand', models.FloatField()),
                ('new_tests_per_thousand', models.FloatField()),
                ('tests_per_case', models.FloatField()),
                ('positive_rate', models.FloatField()),
                ('tests_units', models.TextField()),
                ('stringency_index', models.DecimalField(decimal_places=2, max_digits=5)),
                ('population', models.PositiveBigIntegerField()),
                ('population_density', models.DecimalField(decimal_places=3, max_digits=7)),
                ('median_age', models.DecimalField(decimal_places=1, max_digits=4)),
                ('aged_65_older', models.DecimalField(decimal_places=3, max_digits=6)),
                ('aged_70_older', models.DecimalField(decimal_places=3, max_digits=6)),
                ('gdp_per_capita', models.DecimalField(decimal_places=3, max_digits=9)),
                ('extreme_poverty', models.DecimalField(decimal_places=1, max_digits=4)),
                ('cardiovasc_death_rate', models.DecimalField(decimal_places=3, max_digits=7)),
                ('diabetes_prevalence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('female_smokers', models.DecimalField(decimal_places=3, max_digits=6)),
                ('male_smokers', models.DecimalField(decimal_places=3, max_digits=6)),
                ('handwashing_facilities', models.DecimalField(decimal_places=3, max_digits=6)),
                ('hospital_beds_per_thousand', models.DecimalField(decimal_places=3, max_digits=6)),
                ('life_expectancy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('human_development_index', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
            options={
                'ordering': ['iso_code', 'date'],
            },
        ),
        migrations.AlterModelOptions(
            name='coviddataclean',
            options={'managed': False},
        ),
    ]
