# Generated by Django 3.1.2 on 2020-10-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_created_country_data_view"),
    ]

    operations = [
        migrations.RunSQL(
            """
        create materialized view data_months as
        SELECT DISTINCT date(date_trunc('month'::text, data_coviddataraw.date::timestamp with time zone)) AS month
        FROM data_coviddataraw
        ORDER BY (date(date_trunc('month'::text, data_coviddataraw.date::timestamp with time zone)));

        alter materialized view data_months owner to "DataTitans";""",
            """DROP MATERIALIZED VIEW IF EXISTS data_months""",
        ),
        migrations.RunSQL(
            """
        create materialized view data_coviddatamonthly as
        SELECT DISTINCT data_coviddataclean.iso_code,
                        data_coviddataclean.continent,
                        data_coviddataclean.location,
                        date(date_trunc('month'::text, data_coviddataclean.date::timestamp with time zone))      AS month,
                        sum(data_coviddataclean.new_cases) OVER (PARTITION BY data_coviddataclean.iso_code, (date(
                                date_trunc('month'::text, data_coviddataclean.date::timestamp with time zone)))) AS new_cases,
                        sum(data_coviddataclean.new_deaths) OVER (PARTITION BY data_coviddataclean.iso_code, (date(
                                date_trunc('month'::text, data_coviddataclean.date::timestamp with time zone)))) AS new_deaths,
                        sum(data_coviddataclean.new_tests) OVER (PARTITION BY data_coviddataclean.iso_code, (date(
                                date_trunc('month'::text, data_coviddataclean.date::timestamp with time zone)))) AS new_tests,
                        concat(date(date_trunc('month'::text, data_coviddataclean.date::timestamp with time zone))::text, data_coviddataclean.iso_code) AS data_key
        FROM data_coviddataclean
        ORDER BY data_coviddataclean.iso_code,
                 (date(date_trunc('month'::text, data_coviddataclean.date::timestamp with time zone)));

        alter materialized view data_coviddatamonthly owner to "DataTitans";""",
            """DROP MATERIALIZED VIEW IF EXISTS data_coviddatamonthly""",
        ),
    ]
