# Generated by Django 3.1.2 on 2020-10-31 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_created_monthly_data_view'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE data_coviddataraw
            add column icu_patients numeric,
            add column icu_patients_per_million numeric,
            add column hosp_patients numeric,
            add column hosp_patients_per_million numeric,
            add column weekly_icu_admissions numeric,
            add column weekly_icu_admissions_per_million numeric,
            add column weekly_hosp_admissions numeric,
            add column weekly_hosp_admissions_per_million numeric
            """,
            """
            ALTER TABLE data_coviddataraw
            drop column icu_patients,
            drop column icu_patients_per_million,
            drop column hosp_patients,
            drop column hosp_patients_per_million,
            drop column weekly_icu_admissions,
            drop column weekly_icu_admissions_per_million,
            drop column weekly_hosp_admissions,
            drop column weekly_hosp_admissions_per_million
            """
        )
    ]
