# Generated by Django 3.1.1 on 2020-09-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_coviddataclean_new_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='coviddataclean',
            name='new_cases_smoothed',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coviddataclean',
            name='new_deaths_smoothed',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coviddataclean',
            name='new_tests_smoothed',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coviddataclean',
            name='total_cases',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coviddataclean',
            name='total_deaths',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coviddataclean',
            name='total_tests',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
