# Generated by Django 3.1.1 on 2020-09-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200920_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddataraw',
            name='aged_65_older',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='aged_70_older',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='cardiovasc_death_rate',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='continent',
            field=models.CharField(max_length=15, null=True, unique_for_date='date'),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='diabetes_prevalence',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='extreme_poverty',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='female_smokers',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='gdp_per_capita',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='handwashing_facilities',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='hospital_beds_per_thousand',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='human_development_index',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='iso_code',
            field=models.CharField(max_length=8, null=True, unique_for_date='date'),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='life_expectancy',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='location',
            field=models.CharField(max_length=55, null=True, unique_for_date='date'),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='male_smokers',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='median_age',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='new_cases_per_million',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='new_cases_smoothed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='new_cases_smoothed_per_million',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='new_deaths_per_million',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='new_deaths_smoothed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='new_deaths_smoothed_per_million',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='new_tests_per_thousand',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='population',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='population_density',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='positive_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='stringency_index',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='tests_per_case',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='tests_units',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='total_cases',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='total_cases_per_million',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='total_deaths',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='total_deaths_per_million',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='total_tests',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='total_tests_per_thousand',
            field=models.FloatField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='coviddataraw',
            unique_together={('iso_code', 'date')},
        ),
    ]
