# Generated by Django 3.1.1 on 2020-09-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20200921_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='coviddataclean',
            name='new_cases_per_million',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coviddataclean',
            name='new_cases_smoothed_per_million',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coviddataclean',
            name='new_tests_per_thousand',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coviddataclean',
            name='new_tests_smoothed_per_thousand',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coviddataclean',
            name='population',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coviddataclean',
            name='positive_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='coviddataclean',
            name='stringency_index',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coviddataclean',
            name='tests_per_case',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='coviddataclean',
            name='tests_units',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coviddataclean',
            name='total_cases_per_million',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coviddataclean',
            name='total_tests_per_thousand',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
