# Generated by Django 3.1.1 on 2020-09-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20200920_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='coviddataraw',
            name='new_tests_smoothed',
            field=models.FloatField(null=True),
        ),
    ]
