# Generated by Django 3.1.1 on 2020-09-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200922_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='coviddataclean',
            name='new_deaths_per_million',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coviddataclean',
            name='new_deaths_smoothed_per_million',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coviddataclean',
            name='total_deaths_per_million',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
