# Generated by Django 3.1.1 on 2020-09-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_coviddataraw_new_tests_smoothed'),
    ]

    operations = [
        migrations.AddField(
            model_name='coviddataraw',
            name='new_tests_smoothed_per_thousand',
            field=models.FloatField(null=True),
        ),
    ]
