# Generated by Django 3.1.2 on 2020-11-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0008_refined_monthly_data_query"),
    ]

    operations = [
        migrations.DeleteModel(name="Post",),
    ]
