# Generated by Django 3.1.1 on 2020-09-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20200920_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddataraw',
            name='new_cases',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='new_deaths',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
