# Generated by Django 3.1.1 on 2020-09-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20200928_1915'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coviddataclean',
            index=models.Index(fields=['iso_code', 'date'], name='data_covidd_iso_cod_fda5c0_idx'),
        ),
    ]
