# Generated by Django 3.1.3 on 2020-11-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0010_add_country_aggregations"),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP TABLE IF EXISTS data_coviddataraw CASCADE;
            """
        )
    ]
