# Generated by Django 3.1.1 on 2020-09-21 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20200920_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coviddataclean',
            options={},
        ),
    ]
