# Generated by Django 3.1.1 on 2020-09-21 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20200921_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coviddataclean',
            name='total_cases',
        ),
        migrations.RemoveField(
            model_name='coviddataclean',
            name='total_deaths',
        ),
        migrations.RemoveField(
            model_name='coviddataclean',
            name='total_tests',
        ),
        migrations.AlterField(
            model_name='coviddataclean',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='continents', to='data.coviddataraw'),
        ),
        migrations.AlterField(
            model_name='coviddataclean',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dates', to='data.coviddataraw'),
        ),
        migrations.AlterField(
            model_name='coviddataclean',
            name='iso_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='iso_codes', to='data.coviddataraw'),
        ),
        migrations.AlterField(
            model_name='coviddataclean',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='locations', to='data.coviddataraw'),
        ),
        migrations.AlterField(
            model_name='coviddataclean',
            name='new_cases',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cases', to='data.coviddataraw'),
        ),
        migrations.AlterField(
            model_name='coviddataclean',
            name='new_deaths',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deaths', to='data.coviddataraw'),
        ),
        migrations.AlterField(
            model_name='coviddataclean',
            name='new_tests',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tests', to='data.coviddataraw'),
        ),
    ]
