# Generated by Django 3.1.1 on 2020-10-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20200928_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coviddataclean',
            options={'ordering': ['iso_code', 'date']},
        ),
        migrations.AlterUniqueTogether(
            name='coviddataclean',
            unique_together={('iso_code', 'date')},
        ),
    ]
