# Generated by Django 3.1.3 on 2020-11-16 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_dropped_manual_tables'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='CovidDataClean',
        ),
        migrations.DeleteModel(
            name='CovidDataMonthly',
        ),
        migrations.DeleteModel(
            name='CovidDataRaw',
        ),
        migrations.DeleteModel(
            name='Months',
        ),
    ]
