# Generated by Django 3.1.1 on 2020-10-01 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20201001_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coviddataraw',
            options={'managed': False, 'ordering': ['iso_code', 'date']},
        ),
    ]
