# Generated by Django 3.1.2 on 2020-10-02 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20201001_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coviddataclean',
            name='id',
        ),
        migrations.AddField(
            model_name='coviddataclean',
            name='data_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
