# Generated by Django 3.1.2 on 2020-10-12 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20201010_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidDataMonthly',
            fields=[
                ('iso_code', models.CharField(max_length=8, unique_for_month='month')),
                ('continent', models.CharField(max_length=15, unique_for_month='month')),
                ('location', models.CharField(max_length=55, unique_for_month='month')),
                ('new_cases', models.IntegerField()),
                ('new_deaths', models.IntegerField()),
                ('new_tests', models.IntegerField()),
                ('data_key', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['iso_code', 'month'],
            },
        ),
        migrations.CreateModel(
            name='Months',
            fields=[
                ('month', models.DateField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['month'],
            },
        ),
        migrations.AddIndex(
            model_name='months',
            index=models.Index(fields=['month'], name='data_months_month_6648ad_idx'),
        ),
        migrations.AddField(
            model_name='coviddatamonthly',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.months'),
        ),
        migrations.AddIndex(
            model_name='coviddatamonthly',
            index=models.Index(fields=['iso_code', 'month'], name='data_covidd_iso_cod_b1dd1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coviddatamonthly',
            unique_together={('iso_code', 'month')},
        ),
    ]
