# Generated by Django 3.1.2 on 2020-10-21 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20201012_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coviddataraw',
            options={'ordering': ['iso_code', 'date']},
        ),
    ]
