# Generated by Django 3.1.2 on 2020-10-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20201021_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coviddataraw',
            name='id',
        ),
        migrations.AddField(
            model_name='coviddataraw',
            name='data_key',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coviddataraw',
            name='population_density',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
    ]
