# Generated by Django 3.1.2 on 2020-10-24 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20201021_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='coviddataclean',
            options={'managed': False, 'ordering': ['iso_code', 'date']},
        ),
        migrations.AlterModelOptions(
            name='coviddatamonthly',
            options={'managed': False, 'ordering': ['iso_code', 'month']},
        ),
        migrations.AlterModelOptions(
            name='coviddataraw',
            options={'managed': False, 'ordering': ['iso_code', 'date']},
        ),
        migrations.AlterModelOptions(
            name='months',
            options={'managed': False, 'ordering': ['month']},
        ),
    ]
