# Generated by Django 3.1.2 on 2020-11-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20201110_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='coviddataraw',
            name='reproduction_rate',
            field=models.FloatField(null=True),
        ),
    ]
