# Generated by Django 3.1.3 on 2020-11-22 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0002_auto_20201114_1852"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="blog_id", new_name="blog",
        ),
        migrations.RemoveField(model_name="comment", name="username",),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                default=-1, on_delete=django.db.models.deletion.CASCADE, to="auth.user"
            ),
            preserve_default=False,
        ),
    ]
